### ISSUE TITLE
最后那段不严谨

### ISSUE THREAD

**Issue by ltaoo** [qq20004604/webpack-study#1]
2、简单指令（npm脚本）

“内容如下”，会让人误以为全部都要粘贴进去吧，但是 json 文件不能有注释。

最后 “这个是npm的特性，而不是webpack的，但是webpack基于nodejs所以可用。”
如果我运行的脚本是`node index.js`，那是说 node 是基于 node ？

npm script 的原理就是可以运行一段 shell 命令，webpack 就是一个 shell 命令所以可用更恰当吧。

**Comment by qq20004604** [comment]
严格来说，在linux下是shell命令，但是在win下是doc命令。
其次，我们不管是运行``npm run test``或者是``webpack``，首先他是一段shell命令（假设在linux下），
再者，执行``npm run test``之所以有反应，是因为这段命令调用了npm包管理器，然后根据npm包管理器去找到并执行对应的脚本。

当然，可能我这句话有歧义，所以我已经修改了。
另外，文件内容是基于文件夹里的文件的，如果有人把我写的代码块里的文件直接复制出来使用，那么我应该打他屁股，哈哈
